# Generated by Django 5.0.2 on 2025-05-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', '现金'), ('bank_transfer', '银行转账'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('other', '其他')], max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('rent', '租金'), ('deposit', '押金'), ('utility', '水电费'), ('other', '其他')], max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.tenant')),
            ],
            options={
                'db_table': 'payment_history',
                'ordering': ['-payment_date'],
            },
        ),
    ]
