# Generated by Django 5.0.2 on 2025-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('rent', '租金'), ('water', '水费'), ('electricity', '电费'), ('maintenance', '维修费'), ('other', '其他')], max_length=50, null=True),
        ),
    ]
